### ISSUE TITLE
Readme points at dead links

### ISSUE THREAD

**Issue by Isabello** [RiseVision/rise-node#1]
Most users won't be able to install with the instructions available as the links are dead. Maybe update the readme to use the manager script in the repo or correct the url for the wget.

**Comment by lepetitjan** [comment]
We know, yesterday we wanted to release the commander but found a bug so we put an announcement online to use the manager instead of the commander for now. We will fix it asap. Thanks for opening an issue.

**Comment by Isabello** [comment]
Is this solved with a commit? an announcement is not really good enough if
people aren't on the services to receive it.

**Comment by Isabello** [comment]
other thing, even though the instructions work now, you should remove the `$` so the instructions can be copy pasted easily.

**Comment by lepetitjan** [comment]
I should? The $ is to indicate people should perform the actions as use, not as root. That's a common mistake as you might know. If people even can't copy a string...

**Comment by Isabello** [comment]
It makes the instructions much easier to follow in my view. maybe have a specific step that tells them to su into a non privileged user?

The $ makes it a pain to copy paste.

**Comment by lepetitjan** [comment]
Fixed it [here](https://github.com/RiseVision/rise-node/commit/612f60405c656582cf8f3e7e1324bc89b3bc7b22)
Thanks Isabello
