### ISSUE TITLE
Unused module "helpers/decorators/profile" (profilePromise)

### ISSUE THREAD

**Issue by jarenal** [RiseVision/rise-node#100]
TSLint reported me that the module "helpers/decorators/profile" is not used in the project.

I've searched this module in the whole project but never it is used, so I think we could remove it without issues.

@vekexasia Could you confirm me if is safe to remove this module?

Thanks in advance!

**Comment by vekexasia** [comment]
@jarenal also this is ok to stay. Unused but sometimes I use it in development to have statistics and metics about code execution. :)
