### ISSUE TITLE
Support Node V8

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-node#124]
Node V8 leverages several benefits against V6. For example async/await and class supports. 

**What we'll achieve**
 - Possibly more speed
 - Less dependency on transpilation dependencies
 - Cleaner transpiled code
 - ...

**What needs to be done**:
Some tests are currently written using rewire and tests are failing cause rewire is trying to change a const variable. A [solution](https://github.com/jhnns/rewire/pull/117) was provided by rewire which involves transpiling the code using babel to rewrite const into let. After a little bit of investigation, the heavy lifting is done in `lib/moduleEnv` but only `.js` and `.coffee` extensions are registered leaving typescript untouched.

We should investigate and rewrite tests so that we don't leverage the use of `rewire`

**Comment by mcanever** [comment]
## Unit tests to fix:
- [x] AppManager.spec.ts
- apis
  - [x] accountsAPI.spec.ts
  - [x] blocksAPI.spec.ts
  - [x] transactions.spec.ts
- helpers
  - [x] cache.spec.ts
  - [x] config.spec.ts
  - [x] database.spec.ts
  - [x] ed.spec.ts
  - [x] request-limiter.spec.ts
  - decorators
    - [x] schemavalidators.spec.ts
- logic
  - [x] account.spec.ts
  - [x] appState.spec.ts
  - [x] block.spec.ts
  - [x] peer.spec.ts
  - [x] round.spec.ts
  - [x] transaction.spec.ts
  - transactions
    - [x] createmultisig.spec.ts
    - [x] delegate.spec.ts
- modules
  - [x] cache.spec.ts
  - [x] delegates.spec.ts
  - [x] forge.spec.ts
  - [x] transactions.spec.ts
  - [x] transport.spec.ts
