### ISSUE TITLE
Recreate github repo for source code attribution.

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-node#15]
Currently the history of the repo was taken away when the code was first committed.

It would be nice **and ethically correct**, even if this means to fix #14 and possibly other issues, to clone lisk and apply rise patches to it so that the whole project history comes back to life and proper code attribution gets restored.

**Comment by nerdvibe** [comment]
I strongly agree on this!

**Comment by vekexasia** [comment]
Done
