### ISSUE TITLE
password authentication failed for user "rise"

### ISSUE THREAD

**Issue by anandpatel010** [RiseVision/rise-node#182]
![ss](https://user-images.githubusercontent.com/16581225/41614567-c2414356-73f0-11e8-9151-f44b871275a5.png)

I got this error when trying to run a mainnet node on an Ubuntu virtual machine (16.04) 

Not sure what password it is talking about

**Comment by anandpatel010** [comment]
^^ This was the output of the logs when my DB and node was not running properly.

Here are the commands I was running
![ss](https://user-images.githubusercontent.com/16581225/41614962-de586bae-73f1-11e8-8c3e-4648c7d48178.png)

**Comment by vekexasia** [comment]
Hello @spookiestevie are you running postgres on that srv?

**Comment by anandpatel010** [comment]
![ss](https://user-images.githubusercontent.com/16581225/41617389-422be178-73f8-11e8-979f-5f1b6ea04ba8.png)

To my knowledge, it's installed but not running anything.

**Comment by vekexasia** [comment]
Can you try `sudo netstat -tanp | grep postgres` ?

**Comment by spookiestevie** [comment]
![ss](https://user-images.githubusercontent.com/16581225/41619524-774cc84e-73fe-11e8-9547-6e23f3093cea.png)

**Comment by anandpatel010** [comment]
![ss](https://user-images.githubusercontent.com/16581225/41619568-a47a6e3e-73fe-11e8-8b09-c7923151800f.png)

**Comment by vekexasia** [comment]
sudo ps aux | grep postgres
?

**Comment by jarenal** [comment]
I just installed RISE-NODE following the steps from the README in a clean Ubuntu 16.04 without issues.

![rise-mainnet-test](https://user-images.githubusercontent.com/696774/41621683-a8a9c1bc-740d-11e8-936e-3dcb3ca7feb7.PNG)

**Comment by anandpatel010** [comment]
here is the result of
sudo ps aux | grep postgres
![ss](https://user-images.githubusercontent.com/16581225/41621823-bbb4773c-7405-11e8-82ca-0c08b43c82f7.png)

Yeah, I was just about to try it on a fresh install but I was wondering why it wasn't working on my desktop version ubuntu 16.04

**Comment by vekexasia** [comment]
Postgres is running at system level. That's why it is not properly working unfortunately

**Comment by anandpatel010** [comment]
Ok, no problem. Thanks!
