### ISSUE TITLE
Returned delegate data model differs between endpoints

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-node#188]
Delegate data differs in various endpoints:

- [/accounts/delegates](https://twallet.rise.vision/api/accounts/delegates?address=7851658041862611161R)
- [/delegates](https://twallet.rise.vision/api/delegates) (adds `cmb` field)
- [/delegates/search](https://twallet.rise.vision/api/delegates/search?q=mcanever) (adds `votesWeight`, `voters_cnt` and `register_timestamp` fields; removes `rate` field)

Possibly unify the returned data? Or if some of the search fields are omitted for performance reason, then at least `cmb` ought to be included in the `/accounts/delegates` return data.

@vekexasia added on Slack that `votesWeight` should be included in all as well.

**Comment by mcanever** [comment]
Thx @roosmaa for summarizing this, I'll fix it soon
