### ISSUE TITLE
Failed to use npm start for running RISE node

### ISSUE THREAD

**Issue by 1indian** [RiseVision/rise-node#194]
## Steps to reproduce

- git clone https://github.com/RiseVision/rise-node.git
- `cd rise-node`
- `npm i`
- `npm run transpile`
- `npm strat`

## Actual behaviour
```
❯ npm start

> Rise-node@1.3.4 start /rise-node
> node app.js

module.js:550
    throw err;
    ^

Error: Cannot find module '/rise-node/app.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rise-node@1.3.4 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rise-node@1.3.4 start script.
```

**Comment by vekexasia** [comment]
hey @1indian try with `node dist/app.js`

**Comment by 1indian** [comment]
Thank you @vekexasia , I got the fix, I created this issue so that we can fix it in `package.json` https://github.com/RiseVision/rise-node/blob/9c48391a4297f93159830da20bbe06e44a71ff11/package.json#L6

**Comment by 1indian** [comment]
If I have to give PR, do I need to create PR against `master` branch?

**Comment by vekexasia** [comment]
`development` plz... Thanks :)
