### ISSUE TITLE
gzip: ./latestsnap.gz: unexpected end of file

### ISSUE THREAD

**Issue by anandpatel010** [RiseVision/rise-node#198]
![822de63536e3663a37854d05506fa9d4](https://user-images.githubusercontent.com/16581225/56084443-fa26e080-5e2a-11e9-83fd-c6faf65ed79d.png)

> gzip: ./latestsnap.gz: unexpected end of file

Hi, I encountered this error when running ./manager.sh downloadSnapshot and
./manager.sh restoreBackup

I posted more info on the slack. Currently having to sync from 0
https://risevision.slack.com/archives/C557VNSM6/p1555181555005400

bunch of wierd stuff in node.mainnet.log
![5d3ab5503b0797c761951bd5c158458e](https://user-images.githubusercontent.com/16581225/56084536-22630f00-5e2c-11e9-84a4-9536a06253dd.png)
![ca2bc7286686ae0069b8609b377faf4a](https://user-images.githubusercontent.com/16581225/56084538-25f69600-5e2c-11e9-928a-ca39187477bd.png)

💯 :)

**Comment by vekexasia** [comment]
Fixed. It should be working by the next snapshot (within 24h) 

Thanks for reporting :)
