### ISSUE TITLE
logic/block has an issue in calculateFee() method

### ISSUE THREAD

**Issue by jarenal** [RiseVision/rise-node#20]
Testing logic/block I've noticed that calculateFee() is not working properly. There are an issue when we try to get the fee.

Currently is trying to get the fee so:

`return constants.fees.send;`

but according with the constants module the correct way should be:

`return constants.fees[0].fees.send;`

**Comment by vekexasia** [comment]
As far as I know that method is not used anywhere. It can safely removed (after proper investigation about what I'm saying)

**Comment by jarenal** [comment]
Ok @vekexasia let me know when I could remove it.
