### ISSUE TITLE
logic/vote uses this.scope but was never declared

### ISSUE THREAD

**Issue by jarenal** [RiseVision/rise-node#43]
In logic/vote module we are using this.scope in some parts of code but was never declared. 

For example:

[https://github.com/RiseVision/rise-node/blob/development/logic/vote.js#L260](https://github.com/RiseVision/rise-node/blob/development/logic/vote.js#L260)

[https://github.com/RiseVision/rise-node/blob/development/logic/vote.js#L312](https://github.com/RiseVision/rise-node/blob/development/logic/vote.js#L312)

**Comment by vekexasia** [comment]
After further investigation, it's true that `scope` is never defined within Vote (and other transaction types) but the `undo`, and `undoTransactions` are being called using `.call` in the `logic/transaction` file.

```js
		__private.types[trs.type].undo.call(this, trs, block, sender, function (err) {
			if (err) {
				this.scope.account.merge(sender.address, {
					balance: -amount,
					blockId: block.id,
					round: modules.rounds.calc(block.height)
				}, function (err) {
					return setImmediate(cb, err);
				});
			} else {
				return setImmediate(cb);
			}
		}.bind(this));
```
So, when `Vote.undo` is called the context (or `this`) is from `Transaction` not from `Vote` so this is not a bug but simply a "report" on bad coding practices.
