### ISSUE TITLE
syntax error near unexpected token `>' (./rise_manager.bash install)

### ISSUE THREAD

**Issue by KirillVolkov** [RiseVision/rise-node#5]
./rise_manager.bash: line 55: syntax error near unexpected token `>'
./rise_manager.bash: line 55: `    sudo apt-get install -y -qq curl build-essential python lsb-release wget openssl autoconf libtool automake libsodium-dev &>> $logfile || \'

How to fix it?

Max OS Sierra

**Comment by vekexasia** [comment]
Hello @KirillVolkov thanks for reporting.

We have fixed this in the new version of the core.
