### ISSUE TITLE
Double NOT operator usage (!)

### ISSUE THREAD

**Issue by jarenal** [RiseVision/rise-node#95]
Hi team @RiseVision/developers 

I would like to get your feedback about an issue.

At line 

https://github.com/RiseVision/rise-node/blob/feature/typescript/src/modules/loader.ts#L303

TSLint is reporting that the next expression

`emitBlockchainReady = !!emitBlockchainReady;`

could be simplified to

`emitBlockchainReady = emitBlockchainReady;`

I think that we could remove that line because if **emitBlockchainReady** value is **TRUE** we will get the same value after apply **NOT** operator (!) two times. 

What do you think about it?

Thanks in advance!

**Comment by mcanever** [comment]
Hi @jarenal this looks like an old-school "Cast to boolean" operator. Basically it will force anything "truthy" to true, and the rest to false. I'm not sure about the necessity for that cast, I would track down who in the code calls load() and with which parameters. I think Typescript would catch attempts to pass something different than boolean to that parameter, but better double check anyways!

**Comment by jarenal** [comment]
Hi @mcanever 

Yes, I think you are right.

In theory now, after the migration to TypeScript, the **emitBlockchainReady** always will be **boolean** according the method declaration, look at this:

`public async load(count: number, limitPerIteration: number, message?: string, emitBlockchainReady?: boolean)`

So, in my opinion we could remove that linke safetly.

PS: Thank you for your feedback!

**Comment by jarenal** [comment]
According TS documentation if you don't pass value to an optional parameter its value will be **undefined**, so probably the casting is preventing receive **undefined** and receive **false** instead.

We can fix it setting a default value, so if we don't pass value to that parameter we will receive the default value assigned instead of **undefined**

So I think We could improve that part of code doing this:

Original:

```
  public async load(count: number, limitPerIteration: number, message?: string, emitBlockchainReady?: boolean) {
    let offset          = 0;
    emitBlockchainReady = !!emitBlockchainReady;
    if (message) {
      this.logger.warn(message);
      this.logger.warn('Recreating memory tables');
    }
```

Improvement:

```
  public async load(count: number, limitPerIteration: number, message?: string, emitBlockchainReady = false) {
    let offset          = 0;
    if (message) {
      this.logger.warn(message);
      this.logger.warn('Recreating memory tables');
    }
```

References:

**Optional and default values**: https://www.typescriptlang.org/docs/handbook/functions.html
