### ISSUE TITLE
Unused module "helpers/decorators/debugLog"

### ISSUE THREAD

**Issue by jarenal** [RiseVision/rise-node#99]
TSLint reported me that the module "helpers/decorators/debugLog" is not used in the project.

I've searched this module in the whole project but never it is used, so I think we could remove it without issues.

@vekexasia Could you confirm me if is safe to remove this module?

Thanks in advance!

**Comment by vekexasia** [comment]
It's correct that it is not used. But i sometimes use it to properly debug stuff.
